name: CI/CD - La rifa mas montanera

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |

            cd "${{ secrets.PATH }}"

            git pull origin main
            git fetch

            echo '${{ secrets.ENV_FILE }}' > .env

            sudo apt update
            sudo apt install -y nodejs npm

            composer i
            composer dump-autoload

            php -i | grep "Loaded Configuration File"
            php artisan package:discover --ansi
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            composer clear-cache

            php artisan migrate:fresh --seed
            php artisan optimize:clear
